### ISSUE TITLE
Can we train the SRResNet with the MSE Loss in the VGG19 sapce?

### ISSUE THREAD

**Issue by ANYMS-A** [sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution#15]
It feels like the improvment from SRResNet to SRGAN is mainly caused by that SRGAN calculate the MSELoss under the VGG19's space. Have you ever done any comparison like train the SRResNet with the MSELoss under the VGG19 sapce?

**Comment by sgrvinod** [comment]
No, I have not done such a comparison. I do not know for sure how much the VGG-space content loss and the adversarial loss each individually contribute to the total improvement. If you do such an experiment, please let me know.

I guess the results of that experiment will need to be judged by eye since the metrics don't capture the improvement.

**Comment by ANYMS-A** [comment]
Thanks! I will have a try in the next few days!

**Comment by ANYMS-A** [comment]
Hey I recently trained the SRResNet with the MSE loss under the VGG-space, it seems the super-resolved image will have “regular texture like pattern” like below:

<img width="425" alt="1704871300279" src="https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution/assets/26103763/3958e432-2825-4242-9169-f30ce207f077">

The original HR image look like below:
<img width="539" alt="1704871475949" src="https://github.com/sgrvinod/a-PyTorch-Tutorial-to-Super-Resolution/assets/26103763/a57d3c10-58d9-43ea-8bef-dbd719d1821c">

Do you have any idea about why this happen? Thanks!

**Comment by sgrvinod** [comment]
Thanks for letting me know! 

I'm not entirely sure how this happens in the subpixel convolution, but I think these are checkerboard artifacts that can occur when images are upscaled.

[This article](https://distill.pub/2016/deconv-checkerboard/) provides some examples of how this happens during deconvolution.

**Comment by ANYMS-A** [comment]
Nice article! Thanks for sharing this!
